### PR TITLE
$kwmc space -fExperimental

### PR DESCRIPTION
**Pull request by rubas**
Use `$kwmc space -fExperimental` instead of `$kwmc space -f`

https://koekeishiya.github.io/kwm/kwmc.html#spaces

### CODE REVIEW

**Comment by matthewdias** [comment]
Don't think I will merge this. I use Mission Control fairly frequently, and the Dock process doesn't play nice with `-fExperimental`. This will probably stay the case until I have a better solution for assigning windows to spaces on startup, and for navigating to fullscreen apps.

**Comment by rubas** [comment]
There is no parameter `-f` (anymore) in the current build of kwm.

**Comment by matthewdias** [comment]
you're right, but... ive been using it this whole time... that's strange 😕 . anyway, it still works for me, and experimental is still broken with MC, so i'm gonna keep it i think. lemme do some experimentation.

Edit: yeah, makes trackpad gestures useless as well

**Comment by matthewdias** [comment]
FYI: Reason it was still working is focusing the window after it had been moved properly performed the space transition, so that line was not needed at all. Just removed it.

**Pull request closed without merging**
